# Worklow to update Nino, production bot you see today!

name: Update Production instance
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.dockerignore'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install global packages
        run: npm i -g eslint jest typescript

      - name: Install local packages
        run: npm ci

      - name: Run the linter
        run: npm run lint

      - name: Build the project for any errors
        run: tsc --noEmit

      - name: Run tests with Jest
        run: jest --config jest.config.js --forceExit

      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/nino-prod
            git pull
            rm -fr node_modules
            rm yarn.lock
            yarn
            yarn build
            pm2 restart nino-prod
